[package]
name = "unsafe_op_and_compatibility"
version = "0.1.0"
authors = ["dreamflytly <dreamflytly@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
